# Generated by Django 6.0.4 on 2026-04-22 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='user',
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='access_time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='status',
            field=models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], default='granted', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataresource',
            name='allowed_roles',
            field=models.CharField(default='granted', help_text='Comma-separated roles e.g. admin,auditor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataresource',
            name='sensitivity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ComplianceRule',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
